### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Stretsh** [vite-pwa/docs#105]
I think I found a typo on https://vite-pwa-org.netlify.app/guide/static-assets.html, second paragraph. 

`You can also add another static assets such as...` => `You can also add other static assets such as...`

Please excuse me for being a bit lazy and not wanting to go through the whole forking and checking out and PR-ing, just for two letters, so I'm hoping this report is sufficient for someone who already has everything ready to fix this possible typo.

Btw, if there are other facilities for reporting typos like these, you might want to add those to the Contributing Guidelines too.

**Comment by userquin** [comment]
you can go to the docs page, scroll to bottom and click on [Suggest changes to this page](https://github.com/vite-pwa/docs/edit/main/guide/static-assets.md) link

**Comment by Stretsh** [comment]
Wow! Missed that one completely! Don't need this here, then...

**Comment by Stretsh** [comment]
Closed too soon. Clicking that link brings me to the Github page with a message "You need to fork this repository to propose changes.
Sorry, you’re not able to edit this repository directly—you need to fork it and propose your changes from there instead."

**Comment by userquin** [comment]
you only need to fork the repo, the link will create a new branch

**Comment by Stretsh** [comment]
"only"... Not really, right? As I said, too lazy/not in the mood for the whole fork/change/PR process. So if you or anyone would like to make the change, please do. If not, just consider this typo as reported.

**Comment by userquin** [comment]
@Stretsh thx, fixed https://github.com/vite-pwa/docs/commit/8917eccda8c13c29cd151ae91a0e398e3394eb91
