### ISSUE TITLE
self.skipWaiting is not a function

### ISSUE THREAD

**Issue by fatihkurt** [vite-pwa/docs#118]
I am trying to setup minimal setup vite&react app with configuration `registerType: 'autoUpdate'`.  

`VitePWA({ registerType: 'autoUpdate' })`

I have tried other configuration options for workbox like` skipWaiting: true, clientsClaim: true `but throw same error on page open. This probably leads hitting empty page after deploy unless clear cache or new tab open.

Thanks for help.

Error:
![skipWaitingError](https://github.com/vite-pwa/docs/assets/583653/4225582d-d0c2-491d-a732-96737d9ee861)

**Comment by userquin** [comment]
Why imports in your sw (devOptions in dev server)? are you using injectManfiest strategy?

https://github.com/vite-pwa/vite-plugin-pwa/blob/main/examples/react-router/src/vite-env.d.ts#L4C1-L4C34

**Comment by fatihkurt** [comment]
> Why imports in your sw (devOptions in dev server)? are you using injectManfiest strategy?
> 
> https://github.com/vite-pwa/vite-plugin-pwa/blob/main/examples/react-router/src/vite-env.d.ts#L4C1-L4C34

It is vite preview command for testing on localhost. Same error occurs in live.

**Comment by userquin** [comment]
did you run `vite build`? can you provide minimal reproduction?

**Comment by fatihkurt** [comment]
> did you run `vite build`? can you provide minimal reproduction?

Yes, I run vite build first all packages and apps, then vite preview to serve dist folder. I will try to reproduce on my local

**Comment by userquin** [comment]
you can try opening the app in private browing or removing the current service worker and refresing the page, maybe you have an old sw if the por was the same in dev and in preview.

**Comment by fatihkurt** [comment]
I could not find the root issue but same error throws even injectManifest strategies with workbox-build with `skipWaiting: true` property, but no problem if the property omitted. So, I wrote a vite plugin generate sw before and skipWaiting in code by workbox-window. The issue can be closed.
