### ISSUE TITLE
No workbox debug logs in with `devtools.enabled` and strategy `injectedManifest`

### ISSUE THREAD

**Issue by segevfiner** [vite-pwa/docs#126]
Create a project with strategy `injectedManifest` and any basic service worker utilizing workbox, enable `devtools.enabled` and `devtools.type: "module"`, and see that there are no debug logs from workbox when you load the app, adding the `mode: "development"` setting to VitePWA doesn't help.

**Comment by userquin** [comment]
It is `devOptions`, I can see the workbox modules logs in any example in pwa plugin repo, for example running  `dev` script in the `vue-router` example: workbox modules will use `process.env.NODE_ENV`  to enable/disable logs (dead code elimination)

![imagen](https://github.com/vite-pwa/docs/assets/6311119/e9edb472-f031-45ad-8618-05906e8cb773)
