### ISSUE TITLE
Where to put the manifest generated data?

### ISSUE THREAD

**Issue by wsw70** [vite-pwa/docs#127]
When running `node '.\node_modules\@vite-pwa\assets-generator\bin\pwa-assets-generator.mjs' --preset minimal-2023 .\public\door.svg` I get in the output the "Html Head Links" and the "PWA web manifest icons entry" code (HTML and JSON).

I manually added the header links to my `index.html` but I do not know where to put the `"icons"` JSON so that it is ultimately added to `dist/manifest.webmanifest`.

After building my app and **manually** adding the `"icons"` attribute to the generated `dist/manifest.webmanifest` file the PWA works fine. `dist/manifest.webmanifest` is however recreated at each build, erasing my `"icons"` entry. 

How can I have the two merged at build time? (specifically: merging the `dist/manifest.webmanifest` generated during build with the JSON code I see on the output that I would copy in some file)

**Comment by userquin** [comment]
add `manifest: false` to pwa options if you have custom `public/manifest.webmanifest`.

**Comment by userquin** [comment]
```ts
// vite.config.ts
plugins[VitePWA({
  /* other options */
  manifest: {
    icons: {
    }
  }
}]

**Comment by userquin** [comment]
https://vite-pwa-org.netlify.app/manifest.webmanifest

**Comment by wsw70** [comment]
Thank you for the help. I ended up using your first solution, but I will also investigate the last one (data directly in the configuration file). Thank you!
