### ISSUE TITLE
Vue Documentation

### ISSUE THREAD

**Issue by feamsr00** [vite-pwa/docs#38]
Hello!

I'm sorry this is such a simple question.

https://vite-pwa-org.netlify.app/frameworks/vue.html mentions a module type declaration and provides the contents for `virtual:pwa-register/vue`. What exactly if this file to be named and where is it supposed to live?

It would be awesome if this was also clarified in the docs.

Thanks in advance!

**Comment by userquin** [comment]
@feamsr00 `virtual:pwa-register/vue` is a Vite virtual module, use it as any other static import; you should add ts definition via `vite-plugin-pwa/client` in any `d.ts` file inside src folder via reference, for example `src/src/vite-env.d.ts`:

```ts
/// <reference types="vite/client" />
/// <reference types="vite-plugin-pwa/client" />
/// <reference types="vite-plugin-pwa/info" />
```

or add it inside `compilerOptions.types` in `jsconfig.json` or `tsconfig.json` file:
```json
"compilerOptions": {
  "types": ["vite/client", "vite-plugin-pwa/client", "vite-plugin-pwa/info"]
}
```

You can check this Vue component: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/examples/vue-router/src/ReloadPrompt.vue#L2

You can also check the ReloadPrompt.vue component on the docs, just open the code, the static import can be found also there.

**Comment by userquin** [comment]
@feamsr00 it is there:

![imagen](https://user-images.githubusercontent.com/6311119/229351645-6dda5ea5-81d8-4508-8038-41959f6ebc89.png)
