### ISSUE TITLE
React - Cannot find DTS

### ISSUE THREAD

**Issue by C0ZEN** [vite-pwa/docs#59]
I followed the [React type declarations](https://vite-pwa-org.netlify.app/frameworks/react.html#type-declarations) docs.
Since migrating to Nx 16.4.0 (which adds type check to vite builder), I have the following error while building my app:

```shell
Cannot find type definition file for 'vite-plugin-pwa/react'.
  The file is in the program because:
    Entry point of type library 'vite-plugin-pwa/react' specified in compilerOptions
```

With a config as simple as:

```typescript
"compilerOptions": {
  "types": ["node", "vite/client", "vitest", "vite-plugin-pwa/react"],
},
```

**Comment by userquin** [comment]
@C0ZEN you can check examples folder, there is an example for react. Try adding `src/vite-env.d.ts` to your project using refs https://github.com/vite-pwa/vite-plugin-pwa/blob/main/examples/react-router/src/vite-env.d.ts

**Comment by C0ZEN** [comment]
> @C0ZEN you can check examples folder, there is an example for react. Try adding `src/vite-env.d.ts` to your project using refs https://github.com/vite-pwa/vite-plugin-pwa/blob/main/examples/react-router/src/vite-env.d.ts

I used this syntax to solve the issue:

```typescript
import 'vite-plugin-pwa/react';
import 'vite-plugin-pwa/info';
```

Thank you.
