### ISSUE TITLE
Change background color of maskable icons

### ISSUE THREAD

**Issue by ido-pluto** [vite-pwa/docs#95]
Is there a way to change the background colour of the `maskable-icon` and `apple-touch-icon` files?

After installing the PWA app you can see a white background in the installed app's icon

![image](https://github.com/vite-pwa/docs/assets/50456099/c9e17d96-6824-426b-be2d-df0e8ed71dc8)

**Comment by userquin** [comment]
Check the webmanifest `theme_color` , should match the same color in html head meta `theme-color`, check:
- https://vite-pwa-org.netlify.app/guide/pwa-minimal-requirements.html#web-app-manifest
- https://vite-pwa-org.netlify.app/guide/pwa-minimal-requirements.html#entry-point

If previous configuration doesn0t work, you can use [@vite-pwa/assets-generator](https://github.com/vite-pwa/assets-generator) to create the icons and change the bg color for the maskable pwa assets: https://vite-pwa-org.netlify.app/assets-generator/cli.html

**Comment by ido-pluto** [comment]
Thank you! That works.

I needed to change the `preset` in `pwa-assets.config.ts` to have:

```js
    maskable: {
        resizeOptions: {
            background: '#000'
        }
    },
```

It would be best if it would check the `index.html` or the pwa config in `vite.config.ts` for that colour

For feature reference:
https://vite-pwa-org.netlify.app/assets-generator/cli.html#ios-ipad-splash-screens

**Comment by schwartzman** [comment]
Would be super amazing to actually _include this in the documentation..._
